//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace DebitoAutomatico.PS.ServMetodosSICO {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IServMetodosSICO", Namespace="http://tempuri.org/")]
    public partial class ServMetodosSICO : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback MetodoDevolucionesOperationCompleted;
        
        private System.Threading.SendOrPostCallback PermanenciaOperationCompleted;
        
        private System.Threading.SendOrPostCallback DatosBasicosOperationCompleted;
        
        private System.Threading.SendOrPostCallback FechaActualizacionOperationCompleted;
        
        private System.Threading.SendOrPostCallback ActualizarDatosBasicosOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaAsesorOperationCompleted;
        
        private System.Threading.SendOrPostCallback Itfvtasf3auOperationCompleted;
        
        private System.Threading.SendOrPostCallback ProappaauOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ServMetodosSICO() {
            this.Url = global::DebitoAutomatico.PS.Properties.Settings.Default.DebitoAutomatico_PS_ServMetodosSICO_ServMetodosSICO;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event MetodoDevolucionesCompletedEventHandler MetodoDevolucionesCompleted;
        
        /// <remarks/>
        public event PermanenciaCompletedEventHandler PermanenciaCompleted;
        
        /// <remarks/>
        public event DatosBasicosCompletedEventHandler DatosBasicosCompleted;
        
        /// <remarks/>
        public event FechaActualizacionCompletedEventHandler FechaActualizacionCompleted;
        
        /// <remarks/>
        public event ActualizarDatosBasicosCompletedEventHandler ActualizarDatosBasicosCompleted;
        
        /// <remarks/>
        public event ConsultaAsesorCompletedEventHandler ConsultaAsesorCompleted;
        
        /// <remarks/>
        public event Itfvtasf3auCompletedEventHandler Itfvtasf3auCompleted;
        
        /// <remarks/>
        public event ProappaauCompletedEventHandler ProappaauCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IServMetodosSICO/MetodoDevoluciones", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MetodoDevoluciones([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string FechaInicial, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string FechaFinal) {
            object[] results = this.Invoke("MetodoDevoluciones", new object[] {
                        FechaInicial,
                        FechaFinal});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void MetodoDevolucionesAsync(string FechaInicial, string FechaFinal) {
            this.MetodoDevolucionesAsync(FechaInicial, FechaFinal, null);
        }
        
        /// <remarks/>
        public void MetodoDevolucionesAsync(string FechaInicial, string FechaFinal, object userState) {
            if ((this.MetodoDevolucionesOperationCompleted == null)) {
                this.MetodoDevolucionesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMetodoDevolucionesOperationCompleted);
            }
            this.InvokeAsync("MetodoDevoluciones", new object[] {
                        FechaInicial,
                        FechaFinal}, this.MetodoDevolucionesOperationCompleted, userState);
        }
        
        private void OnMetodoDevolucionesOperationCompleted(object arg) {
            if ((this.MetodoDevolucionesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MetodoDevolucionesCompleted(this, new MetodoDevolucionesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IServMetodosSICO/Permanencia", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Permanencia([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Estructura, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string FechaInicial, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string FechaFinal) {
            object[] results = this.Invoke("Permanencia", new object[] {
                        Estructura,
                        FechaInicial,
                        FechaFinal});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PermanenciaAsync(string Estructura, string FechaInicial, string FechaFinal) {
            this.PermanenciaAsync(Estructura, FechaInicial, FechaFinal, null);
        }
        
        /// <remarks/>
        public void PermanenciaAsync(string Estructura, string FechaInicial, string FechaFinal, object userState) {
            if ((this.PermanenciaOperationCompleted == null)) {
                this.PermanenciaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPermanenciaOperationCompleted);
            }
            this.InvokeAsync("Permanencia", new object[] {
                        Estructura,
                        FechaInicial,
                        FechaFinal}, this.PermanenciaOperationCompleted, userState);
        }
        
        private void OnPermanenciaOperationCompleted(object arg) {
            if ((this.PermanenciaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PermanenciaCompleted(this, new PermanenciaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IServMetodosSICO/DatosBasicos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DatosBasicos([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Cupo) {
            object[] results = this.Invoke("DatosBasicos", new object[] {
                        Cupo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DatosBasicosAsync(string Cupo) {
            this.DatosBasicosAsync(Cupo, null);
        }
        
        /// <remarks/>
        public void DatosBasicosAsync(string Cupo, object userState) {
            if ((this.DatosBasicosOperationCompleted == null)) {
                this.DatosBasicosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDatosBasicosOperationCompleted);
            }
            this.InvokeAsync("DatosBasicos", new object[] {
                        Cupo}, this.DatosBasicosOperationCompleted, userState);
        }
        
        private void OnDatosBasicosOperationCompleted(object arg) {
            if ((this.DatosBasicosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DatosBasicosCompleted(this, new DatosBasicosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IServMetodosSICO/FechaActualizacion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string FechaActualizacion([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Cupo) {
            object[] results = this.Invoke("FechaActualizacion", new object[] {
                        Cupo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void FechaActualizacionAsync(string Cupo) {
            this.FechaActualizacionAsync(Cupo, null);
        }
        
        /// <remarks/>
        public void FechaActualizacionAsync(string Cupo, object userState) {
            if ((this.FechaActualizacionOperationCompleted == null)) {
                this.FechaActualizacionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFechaActualizacionOperationCompleted);
            }
            this.InvokeAsync("FechaActualizacion", new object[] {
                        Cupo}, this.FechaActualizacionOperationCompleted, userState);
        }
        
        private void OnFechaActualizacionOperationCompleted(object arg) {
            if ((this.FechaActualizacionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FechaActualizacionCompleted(this, new FechaActualizacionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IServMetodosSICO/ActualizarDatosBasicos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ActualizarDatosBasicos(
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string TipoDocumento, 
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string NumeroDocumento, 
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Cupo, 
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string DireccionResidencia, 
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string DireccionResidencia2, 
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Departamento, 
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Ciudad, 
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Telefono, 
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Celular, 
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Mail, 
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string DireccionEnv, 
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string EnviaFactura, 
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string DireccionOficina, 
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string DireccionOficina2, 
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string DepartamentoOficina, 
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string CiudadOficina, 
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string TelefonoOficina, 
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Extension) {
            object[] results = this.Invoke("ActualizarDatosBasicos", new object[] {
                        TipoDocumento,
                        NumeroDocumento,
                        Cupo,
                        DireccionResidencia,
                        DireccionResidencia2,
                        Departamento,
                        Ciudad,
                        Telefono,
                        Celular,
                        Mail,
                        DireccionEnv,
                        EnviaFactura,
                        DireccionOficina,
                        DireccionOficina2,
                        DepartamentoOficina,
                        CiudadOficina,
                        TelefonoOficina,
                        Extension});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ActualizarDatosBasicosAsync(
                    string TipoDocumento, 
                    string NumeroDocumento, 
                    string Cupo, 
                    string DireccionResidencia, 
                    string DireccionResidencia2, 
                    string Departamento, 
                    string Ciudad, 
                    string Telefono, 
                    string Celular, 
                    string Mail, 
                    string DireccionEnv, 
                    string EnviaFactura, 
                    string DireccionOficina, 
                    string DireccionOficina2, 
                    string DepartamentoOficina, 
                    string CiudadOficina, 
                    string TelefonoOficina, 
                    string Extension) {
            this.ActualizarDatosBasicosAsync(TipoDocumento, NumeroDocumento, Cupo, DireccionResidencia, DireccionResidencia2, Departamento, Ciudad, Telefono, Celular, Mail, DireccionEnv, EnviaFactura, DireccionOficina, DireccionOficina2, DepartamentoOficina, CiudadOficina, TelefonoOficina, Extension, null);
        }
        
        /// <remarks/>
        public void ActualizarDatosBasicosAsync(
                    string TipoDocumento, 
                    string NumeroDocumento, 
                    string Cupo, 
                    string DireccionResidencia, 
                    string DireccionResidencia2, 
                    string Departamento, 
                    string Ciudad, 
                    string Telefono, 
                    string Celular, 
                    string Mail, 
                    string DireccionEnv, 
                    string EnviaFactura, 
                    string DireccionOficina, 
                    string DireccionOficina2, 
                    string DepartamentoOficina, 
                    string CiudadOficina, 
                    string TelefonoOficina, 
                    string Extension, 
                    object userState) {
            if ((this.ActualizarDatosBasicosOperationCompleted == null)) {
                this.ActualizarDatosBasicosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnActualizarDatosBasicosOperationCompleted);
            }
            this.InvokeAsync("ActualizarDatosBasicos", new object[] {
                        TipoDocumento,
                        NumeroDocumento,
                        Cupo,
                        DireccionResidencia,
                        DireccionResidencia2,
                        Departamento,
                        Ciudad,
                        Telefono,
                        Celular,
                        Mail,
                        DireccionEnv,
                        EnviaFactura,
                        DireccionOficina,
                        DireccionOficina2,
                        DepartamentoOficina,
                        CiudadOficina,
                        TelefonoOficina,
                        Extension}, this.ActualizarDatosBasicosOperationCompleted, userState);
        }
        
        private void OnActualizarDatosBasicosOperationCompleted(object arg) {
            if ((this.ActualizarDatosBasicosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ActualizarDatosBasicosCompleted(this, new ActualizarDatosBasicosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IServMetodosSICO/ConsultaAsesor", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ConsultaAsesor([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Codigo) {
            object[] results = this.Invoke("ConsultaAsesor", new object[] {
                        Codigo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaAsesorAsync(string Codigo) {
            this.ConsultaAsesorAsync(Codigo, null);
        }
        
        /// <remarks/>
        public void ConsultaAsesorAsync(string Codigo, object userState) {
            if ((this.ConsultaAsesorOperationCompleted == null)) {
                this.ConsultaAsesorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaAsesorOperationCompleted);
            }
            this.InvokeAsync("ConsultaAsesor", new object[] {
                        Codigo}, this.ConsultaAsesorOperationCompleted, userState);
        }
        
        private void OnConsultaAsesorOperationCompleted(object arg) {
            if ((this.ConsultaAsesorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaAsesorCompleted(this, new ConsultaAsesorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IServMetodosSICO/Itfvtasf3au", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Itfvtasf3au([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Lote) {
            object[] results = this.Invoke("Itfvtasf3au", new object[] {
                        Lote});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Itfvtasf3auAsync(string Lote) {
            this.Itfvtasf3auAsync(Lote, null);
        }
        
        /// <remarks/>
        public void Itfvtasf3auAsync(string Lote, object userState) {
            if ((this.Itfvtasf3auOperationCompleted == null)) {
                this.Itfvtasf3auOperationCompleted = new System.Threading.SendOrPostCallback(this.OnItfvtasf3auOperationCompleted);
            }
            this.InvokeAsync("Itfvtasf3au", new object[] {
                        Lote}, this.Itfvtasf3auOperationCompleted, userState);
        }
        
        private void OnItfvtasf3auOperationCompleted(object arg) {
            if ((this.Itfvtasf3auCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Itfvtasf3auCompleted(this, new Itfvtasf3auCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IServMetodosSICO/Proappaau", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Proappaau([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Archivo) {
            object[] results = this.Invoke("Proappaau", new object[] {
                        Archivo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ProappaauAsync(string Archivo) {
            this.ProappaauAsync(Archivo, null);
        }
        
        /// <remarks/>
        public void ProappaauAsync(string Archivo, object userState) {
            if ((this.ProappaauOperationCompleted == null)) {
                this.ProappaauOperationCompleted = new System.Threading.SendOrPostCallback(this.OnProappaauOperationCompleted);
            }
            this.InvokeAsync("Proappaau", new object[] {
                        Archivo}, this.ProappaauOperationCompleted, userState);
        }
        
        private void OnProappaauOperationCompleted(object arg) {
            if ((this.ProappaauCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ProappaauCompleted(this, new ProappaauCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void MetodoDevolucionesCompletedEventHandler(object sender, MetodoDevolucionesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MetodoDevolucionesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MetodoDevolucionesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void PermanenciaCompletedEventHandler(object sender, PermanenciaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PermanenciaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PermanenciaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void DatosBasicosCompletedEventHandler(object sender, DatosBasicosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DatosBasicosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DatosBasicosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void FechaActualizacionCompletedEventHandler(object sender, FechaActualizacionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FechaActualizacionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FechaActualizacionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ActualizarDatosBasicosCompletedEventHandler(object sender, ActualizarDatosBasicosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ActualizarDatosBasicosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ActualizarDatosBasicosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ConsultaAsesorCompletedEventHandler(object sender, ConsultaAsesorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaAsesorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaAsesorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void Itfvtasf3auCompletedEventHandler(object sender, Itfvtasf3auCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Itfvtasf3auCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Itfvtasf3auCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ProappaauCompletedEventHandler(object sender, ProappaauCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ProappaauCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ProappaauCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591