//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServicioDebito {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Recursos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Recursos() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WcfServicioDebito.Recursos", typeof(Recursos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario o password incorrecto..
        /// </summary>
        internal static string AutenticacionErrada {
            get {
                return ResourceManager.GetString("AutenticacionErrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El banco que tenia el cliente ya no se encuentra activo por favor validar, Banco:.
        /// </summary>
        internal static string BancoInactivo {
            get {
                return ResourceManager.GetString("BancoInactivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contrato N°:.
        /// </summary>
        internal static string Contrato {
            get {
                return ResourceManager.GetString("Contrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solo se pueden ingresar contratos a Débito Automático en Estados Vigente, Mora o Reemplazado..
        /// </summary>
        internal static string ContratoEstados {
            get {
                return ResourceManager.GetString("ContratoEstados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ya fue ingresado como Débito Automático Inconsistente..
        /// </summary>
        internal static string ContratoInconsistente {
            get {
                return ResourceManager.GetString("ContratoInconsistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ya fue ingresado para realizarle el Débito Automático..
        /// </summary>
        internal static string ContratoIngresado {
            get {
                return ResourceManager.GetString("ContratoIngresado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recuerda que la cuenta autorizada debe estar a tu nombre..
        /// </summary>
        internal static string ContratoPuedeCrearse {
            get {
                return ResourceManager.GetString("ContratoPuedeCrearse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrio un incidente, por favor comuniquese con el administrador del sistema..
        /// </summary>
        internal static string ErrorProceso {
            get {
                return ResourceManager.GetString("ErrorProceso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La fecha hábil que tenia el cliente ya no esta activa, por favor validar, Fecha: .
        /// </summary>
        internal static string FechaInactiva {
            get {
                return ResourceManager.GetString("FechaInactiva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La información se consulto correctamente..
        /// </summary>
        internal static string InformacionRetornada {
            get {
                return ResourceManager.GetString("InformacionRetornada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a a Débito Automático!, tu solicitud está en trámite. Pronto te confirmaremos la Activación del Servicio..
        /// </summary>
        internal static string InscripcionClienteNuevo {
            get {
                return ResourceManager.GetString("InscripcionClienteNuevo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a a Débito Automático!, tu solicitud está en trámite. Recuerda ingresar a la plataforma del Banco BBVA  para autorizar este servicio en tu Cuenta y pronto te confirmaremos la Activación del Servicio..
        /// </summary>
        internal static string InscripcionClienteNuevoBBVA {
            get {
                return ResourceManager.GetString("InscripcionClienteNuevoBBVA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Opción no habilitada para el estado actual de tú plan, por favor comunícate con nuestra línea de Servicio al Cliente en Bogotá 376 91 20 y en el resto del país 018000 910 747..
        /// </summary>
        internal static string TerminacionContrato {
            get {
                return ResourceManager.GetString("TerminacionContrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solo se pueden ingresar contratos a Débito Automático con tipos de clientes Suscriptores, Adjudicados o Ganadores y Cuotas por devolver..
        /// </summary>
        internal static string TiposClientes {
            get {
                return ResourceManager.GetString("TiposClientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a tú modificación está en trámite pronto te confirmaremos la activación del servicio. *Si tú modificación es de fecha, no recibirás confirmación..
        /// </summary>
        internal static string UsuarioActualizado {
            get {
                return ResourceManager.GetString("UsuarioActualizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a tú modificación está en trámite. Pronto te confirmaremos la activación del servicio. Recuerda ingresar a la plataforma del Banco BBVA para autorizar este servicio en tú cuenta. *Si tú modificación es de fecha, no recibirás confirmación..
        /// </summary>
        internal static string UsuarioActualizadoBBVA {
            get {
                return ResourceManager.GetString("UsuarioActualizadoBBVA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tú activación a este servicio está pendiente, estamos validando con tú banco..
        /// </summary>
        internal static string UsuarioActualizadoPendiente {
            get {
                return ResourceManager.GetString("UsuarioActualizadoPendiente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de contrato no existe, por favor validar de nuevo..
        /// </summary>
        internal static string UsuarioNoExiste {
            get {
                return ResourceManager.GetString("UsuarioNoExiste", resourceCulture);
            }
        }
    }
}
