//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace DebitoAutomatico.PS.ServiceDebito {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IServicioDebito", Namespace="http://tempuri.org/")]
    public partial class ServiceDebito : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback IdBancoOperationCompleted;
        
        private System.Threading.SendOrPostCallback TipoCuentaOperationCompleted;
        
        private System.Threading.SendOrPostCallback FechaDebitoOperationCompleted;
        
        private System.Threading.SendOrPostCallback CanalIngresoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaClienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback GuardarClienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback ModificarDatosOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaClientePrenotaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaClienteContratoDigitalOperationCompleted;
        
        private System.Threading.SendOrPostCallback ModificarDatosContratoDigitalOperationCompleted;
        
        private System.Threading.SendOrPostCallback GuardarClienteContratoDigitalOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ServiceDebito() {
            this.Url = global::DebitoAutomatico.PS.Properties.Settings.Default.DebitoAutomatico_PS_ServiceDebito_ServiceDebito;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event IdBancoCompletedEventHandler IdBancoCompleted;
        
        /// <remarks/>
        public event TipoCuentaCompletedEventHandler TipoCuentaCompleted;
        
        /// <remarks/>
        public event FechaDebitoCompletedEventHandler FechaDebitoCompleted;
        
        /// <remarks/>
        public event CanalIngresoCompletedEventHandler CanalIngresoCompleted;
        
        /// <remarks/>
        public event ConsultaClienteCompletedEventHandler ConsultaClienteCompleted;
        
        /// <remarks/>
        public event GuardarClienteCompletedEventHandler GuardarClienteCompleted;
        
        /// <remarks/>
        public event ModificarDatosCompletedEventHandler ModificarDatosCompleted;
        
        /// <remarks/>
        public event ConsultaClientePrenotaCompletedEventHandler ConsultaClientePrenotaCompleted;
        
        /// <remarks/>
        public event ConsultaClienteContratoDigitalCompletedEventHandler ConsultaClienteContratoDigitalCompleted;
        
        /// <remarks/>
        public event ModificarDatosContratoDigitalCompletedEventHandler ModificarDatosContratoDigitalCompleted;
        
        /// <remarks/>
        public event GuardarClienteContratoDigitalCompletedEventHandler GuardarClienteContratoDigitalCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IServicioDebito/IdBanco", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string IdBanco([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Usuario, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Password) {
            object[] results = this.Invoke("IdBanco", new object[] {
                        Usuario,
                        Password});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void IdBancoAsync(string Usuario, string Password) {
            this.IdBancoAsync(Usuario, Password, null);
        }
        
        /// <remarks/>
        public void IdBancoAsync(string Usuario, string Password, object userState) {
            if ((this.IdBancoOperationCompleted == null)) {
                this.IdBancoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIdBancoOperationCompleted);
            }
            this.InvokeAsync("IdBanco", new object[] {
                        Usuario,
                        Password}, this.IdBancoOperationCompleted, userState);
        }
        
        private void OnIdBancoOperationCompleted(object arg) {
            if ((this.IdBancoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IdBancoCompleted(this, new IdBancoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IServicioDebito/TipoCuenta", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TipoCuenta([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Usuario, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Password) {
            object[] results = this.Invoke("TipoCuenta", new object[] {
                        Usuario,
                        Password});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TipoCuentaAsync(string Usuario, string Password) {
            this.TipoCuentaAsync(Usuario, Password, null);
        }
        
        /// <remarks/>
        public void TipoCuentaAsync(string Usuario, string Password, object userState) {
            if ((this.TipoCuentaOperationCompleted == null)) {
                this.TipoCuentaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTipoCuentaOperationCompleted);
            }
            this.InvokeAsync("TipoCuenta", new object[] {
                        Usuario,
                        Password}, this.TipoCuentaOperationCompleted, userState);
        }
        
        private void OnTipoCuentaOperationCompleted(object arg) {
            if ((this.TipoCuentaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TipoCuentaCompleted(this, new TipoCuentaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IServicioDebito/FechaDebito", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string FechaDebito([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Usuario, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Password) {
            object[] results = this.Invoke("FechaDebito", new object[] {
                        Usuario,
                        Password});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void FechaDebitoAsync(string Usuario, string Password) {
            this.FechaDebitoAsync(Usuario, Password, null);
        }
        
        /// <remarks/>
        public void FechaDebitoAsync(string Usuario, string Password, object userState) {
            if ((this.FechaDebitoOperationCompleted == null)) {
                this.FechaDebitoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFechaDebitoOperationCompleted);
            }
            this.InvokeAsync("FechaDebito", new object[] {
                        Usuario,
                        Password}, this.FechaDebitoOperationCompleted, userState);
        }
        
        private void OnFechaDebitoOperationCompleted(object arg) {
            if ((this.FechaDebitoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FechaDebitoCompleted(this, new FechaDebitoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IServicioDebito/CanalIngreso", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CanalIngreso([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Usuario, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Password) {
            object[] results = this.Invoke("CanalIngreso", new object[] {
                        Usuario,
                        Password});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CanalIngresoAsync(string Usuario, string Password) {
            this.CanalIngresoAsync(Usuario, Password, null);
        }
        
        /// <remarks/>
        public void CanalIngresoAsync(string Usuario, string Password, object userState) {
            if ((this.CanalIngresoOperationCompleted == null)) {
                this.CanalIngresoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCanalIngresoOperationCompleted);
            }
            this.InvokeAsync("CanalIngreso", new object[] {
                        Usuario,
                        Password}, this.CanalIngresoOperationCompleted, userState);
        }
        
        private void OnCanalIngresoOperationCompleted(object arg) {
            if ((this.CanalIngresoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CanalIngresoCompleted(this, new CanalIngresoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IServicioDebito/ConsultaCliente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ConsultaCliente(int Contrato, [System.Xml.Serialization.XmlIgnoreAttribute()] bool ContratoSpecified, int IdTitularCuenta, [System.Xml.Serialization.XmlIgnoreAttribute()] bool IdTitularCuentaSpecified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Usuario, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Password) {
            object[] results = this.Invoke("ConsultaCliente", new object[] {
                        Contrato,
                        ContratoSpecified,
                        IdTitularCuenta,
                        IdTitularCuentaSpecified,
                        Usuario,
                        Password});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaClienteAsync(int Contrato, bool ContratoSpecified, int IdTitularCuenta, bool IdTitularCuentaSpecified, string Usuario, string Password) {
            this.ConsultaClienteAsync(Contrato, ContratoSpecified, IdTitularCuenta, IdTitularCuentaSpecified, Usuario, Password, null);
        }
        
        /// <remarks/>
        public void ConsultaClienteAsync(int Contrato, bool ContratoSpecified, int IdTitularCuenta, bool IdTitularCuentaSpecified, string Usuario, string Password, object userState) {
            if ((this.ConsultaClienteOperationCompleted == null)) {
                this.ConsultaClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaClienteOperationCompleted);
            }
            this.InvokeAsync("ConsultaCliente", new object[] {
                        Contrato,
                        ContratoSpecified,
                        IdTitularCuenta,
                        IdTitularCuentaSpecified,
                        Usuario,
                        Password}, this.ConsultaClienteOperationCompleted, userState);
        }
        
        private void OnConsultaClienteOperationCompleted(object arg) {
            if ((this.ConsultaClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaClienteCompleted(this, new ConsultaClienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IServicioDebito/GuardarCliente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GuardarCliente(
                    int Contrato, 
                    [System.Xml.Serialization.XmlIgnoreAttribute()] bool ContratoSpecified, 
                    [System.Xml.Serialization.XmlElementAttribute("IdBanco")] int IdBanco1, 
                    [System.Xml.Serialization.XmlElementAttribute("IdBanco")] [System.Xml.Serialization.XmlIgnoreAttribute()] bool IdBanco1Specified, 
                    [System.Xml.Serialization.XmlElementAttribute("TipoCuenta")] int TipoCuenta1, 
                    [System.Xml.Serialization.XmlElementAttribute("TipoCuenta")] [System.Xml.Serialization.XmlIgnoreAttribute()] bool TipoCuenta1Specified, 
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string NumeroCuenta, 
                    [System.Xml.Serialization.XmlElementAttribute("CanalIngreso")] int CanalIngreso1, 
                    [System.Xml.Serialization.XmlElementAttribute("CanalIngreso")] [System.Xml.Serialization.XmlIgnoreAttribute()] bool CanalIngreso1Specified, 
                    bool Tercero, 
                    [System.Xml.Serialization.XmlIgnoreAttribute()] bool TerceroSpecified, 
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string NombreTercero, 
                    long IdentificacionTercero, 
                    [System.Xml.Serialization.XmlIgnoreAttribute()] bool IdentificacionTerceroSpecified, 
                    int TipoIdTercero, 
                    [System.Xml.Serialization.XmlIgnoreAttribute()] bool TipoIdTerceroSpecified, 
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string DireccionIp, 
                    [System.Xml.Serialization.XmlElementAttribute("FechaDebito")] int FechaDebito1, 
                    [System.Xml.Serialization.XmlElementAttribute("FechaDebito")] [System.Xml.Serialization.XmlIgnoreAttribute()] bool FechaDebito1Specified, 
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Usuario, 
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Password) {
            object[] results = this.Invoke("GuardarCliente", new object[] {
                        Contrato,
                        ContratoSpecified,
                        IdBanco1,
                        IdBanco1Specified,
                        TipoCuenta1,
                        TipoCuenta1Specified,
                        NumeroCuenta,
                        CanalIngreso1,
                        CanalIngreso1Specified,
                        Tercero,
                        TerceroSpecified,
                        NombreTercero,
                        IdentificacionTercero,
                        IdentificacionTerceroSpecified,
                        TipoIdTercero,
                        TipoIdTerceroSpecified,
                        DireccionIp,
                        FechaDebito1,
                        FechaDebito1Specified,
                        Usuario,
                        Password});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GuardarClienteAsync(
                    int Contrato, 
                    bool ContratoSpecified, 
                    int IdBanco1, 
                    bool IdBanco1Specified, 
                    int TipoCuenta1, 
                    bool TipoCuenta1Specified, 
                    string NumeroCuenta, 
                    int CanalIngreso1, 
                    bool CanalIngreso1Specified, 
                    bool Tercero, 
                    bool TerceroSpecified, 
                    string NombreTercero, 
                    long IdentificacionTercero, 
                    bool IdentificacionTerceroSpecified, 
                    int TipoIdTercero, 
                    bool TipoIdTerceroSpecified, 
                    string DireccionIp, 
                    int FechaDebito1, 
                    bool FechaDebito1Specified, 
                    string Usuario, 
                    string Password) {
            this.GuardarClienteAsync(Contrato, ContratoSpecified, IdBanco1, IdBanco1Specified, TipoCuenta1, TipoCuenta1Specified, NumeroCuenta, CanalIngreso1, CanalIngreso1Specified, Tercero, TerceroSpecified, NombreTercero, IdentificacionTercero, IdentificacionTerceroSpecified, TipoIdTercero, TipoIdTerceroSpecified, DireccionIp, FechaDebito1, FechaDebito1Specified, Usuario, Password, null);
        }
        
        /// <remarks/>
        public void GuardarClienteAsync(
                    int Contrato, 
                    bool ContratoSpecified, 
                    int IdBanco1, 
                    bool IdBanco1Specified, 
                    int TipoCuenta1, 
                    bool TipoCuenta1Specified, 
                    string NumeroCuenta, 
                    int CanalIngreso1, 
                    bool CanalIngreso1Specified, 
                    bool Tercero, 
                    bool TerceroSpecified, 
                    string NombreTercero, 
                    long IdentificacionTercero, 
                    bool IdentificacionTerceroSpecified, 
                    int TipoIdTercero, 
                    bool TipoIdTerceroSpecified, 
                    string DireccionIp, 
                    int FechaDebito1, 
                    bool FechaDebito1Specified, 
                    string Usuario, 
                    string Password, 
                    object userState) {
            if ((this.GuardarClienteOperationCompleted == null)) {
                this.GuardarClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGuardarClienteOperationCompleted);
            }
            this.InvokeAsync("GuardarCliente", new object[] {
                        Contrato,
                        ContratoSpecified,
                        IdBanco1,
                        IdBanco1Specified,
                        TipoCuenta1,
                        TipoCuenta1Specified,
                        NumeroCuenta,
                        CanalIngreso1,
                        CanalIngreso1Specified,
                        Tercero,
                        TerceroSpecified,
                        NombreTercero,
                        IdentificacionTercero,
                        IdentificacionTerceroSpecified,
                        TipoIdTercero,
                        TipoIdTerceroSpecified,
                        DireccionIp,
                        FechaDebito1,
                        FechaDebito1Specified,
                        Usuario,
                        Password}, this.GuardarClienteOperationCompleted, userState);
        }
        
        private void OnGuardarClienteOperationCompleted(object arg) {
            if ((this.GuardarClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GuardarClienteCompleted(this, new GuardarClienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IServicioDebito/ModificarDatos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ModificarDatos(int Contrato, [System.Xml.Serialization.XmlIgnoreAttribute()] bool ContratoSpecified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string NumeroCuenta, [System.Xml.Serialization.XmlElementAttribute("TipoCuenta")] int TipoCuenta1, [System.Xml.Serialization.XmlElementAttribute("TipoCuenta")] [System.Xml.Serialization.XmlIgnoreAttribute()] bool TipoCuenta1Specified, [System.Xml.Serialization.XmlElementAttribute("IdBanco")] int IdBanco1, [System.Xml.Serialization.XmlElementAttribute("IdBanco")] [System.Xml.Serialization.XmlIgnoreAttribute()] bool IdBanco1Specified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string DireccionIp, [System.Xml.Serialization.XmlElementAttribute("FechaDebito")] int FechaDebito1, [System.Xml.Serialization.XmlElementAttribute("FechaDebito")] [System.Xml.Serialization.XmlIgnoreAttribute()] bool FechaDebito1Specified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Usuario, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Password) {
            object[] results = this.Invoke("ModificarDatos", new object[] {
                        Contrato,
                        ContratoSpecified,
                        NumeroCuenta,
                        TipoCuenta1,
                        TipoCuenta1Specified,
                        IdBanco1,
                        IdBanco1Specified,
                        DireccionIp,
                        FechaDebito1,
                        FechaDebito1Specified,
                        Usuario,
                        Password});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ModificarDatosAsync(int Contrato, bool ContratoSpecified, string NumeroCuenta, int TipoCuenta1, bool TipoCuenta1Specified, int IdBanco1, bool IdBanco1Specified, string DireccionIp, int FechaDebito1, bool FechaDebito1Specified, string Usuario, string Password) {
            this.ModificarDatosAsync(Contrato, ContratoSpecified, NumeroCuenta, TipoCuenta1, TipoCuenta1Specified, IdBanco1, IdBanco1Specified, DireccionIp, FechaDebito1, FechaDebito1Specified, Usuario, Password, null);
        }
        
        /// <remarks/>
        public void ModificarDatosAsync(int Contrato, bool ContratoSpecified, string NumeroCuenta, int TipoCuenta1, bool TipoCuenta1Specified, int IdBanco1, bool IdBanco1Specified, string DireccionIp, int FechaDebito1, bool FechaDebito1Specified, string Usuario, string Password, object userState) {
            if ((this.ModificarDatosOperationCompleted == null)) {
                this.ModificarDatosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnModificarDatosOperationCompleted);
            }
            this.InvokeAsync("ModificarDatos", new object[] {
                        Contrato,
                        ContratoSpecified,
                        NumeroCuenta,
                        TipoCuenta1,
                        TipoCuenta1Specified,
                        IdBanco1,
                        IdBanco1Specified,
                        DireccionIp,
                        FechaDebito1,
                        FechaDebito1Specified,
                        Usuario,
                        Password}, this.ModificarDatosOperationCompleted, userState);
        }
        
        private void OnModificarDatosOperationCompleted(object arg) {
            if ((this.ModificarDatosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ModificarDatosCompleted(this, new ModificarDatosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IServicioDebito/ConsultaClientePrenota", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ConsultaClientePrenota(int Contrato, [System.Xml.Serialization.XmlIgnoreAttribute()] bool ContratoSpecified) {
            object[] results = this.Invoke("ConsultaClientePrenota", new object[] {
                        Contrato,
                        ContratoSpecified});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaClientePrenotaAsync(int Contrato, bool ContratoSpecified) {
            this.ConsultaClientePrenotaAsync(Contrato, ContratoSpecified, null);
        }
        
        /// <remarks/>
        public void ConsultaClientePrenotaAsync(int Contrato, bool ContratoSpecified, object userState) {
            if ((this.ConsultaClientePrenotaOperationCompleted == null)) {
                this.ConsultaClientePrenotaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaClientePrenotaOperationCompleted);
            }
            this.InvokeAsync("ConsultaClientePrenota", new object[] {
                        Contrato,
                        ContratoSpecified}, this.ConsultaClientePrenotaOperationCompleted, userState);
        }
        
        private void OnConsultaClientePrenotaOperationCompleted(object arg) {
            if ((this.ConsultaClientePrenotaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaClientePrenotaCompleted(this, new ConsultaClientePrenotaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IServicioDebito/ConsultaClienteContratoDigital", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ConsultaClienteContratoDigital(int Contrato, [System.Xml.Serialization.XmlIgnoreAttribute()] bool ContratoSpecified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Usuario, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Password) {
            object[] results = this.Invoke("ConsultaClienteContratoDigital", new object[] {
                        Contrato,
                        ContratoSpecified,
                        Usuario,
                        Password});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaClienteContratoDigitalAsync(int Contrato, bool ContratoSpecified, string Usuario, string Password) {
            this.ConsultaClienteContratoDigitalAsync(Contrato, ContratoSpecified, Usuario, Password, null);
        }
        
        /// <remarks/>
        public void ConsultaClienteContratoDigitalAsync(int Contrato, bool ContratoSpecified, string Usuario, string Password, object userState) {
            if ((this.ConsultaClienteContratoDigitalOperationCompleted == null)) {
                this.ConsultaClienteContratoDigitalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaClienteContratoDigitalOperationCompleted);
            }
            this.InvokeAsync("ConsultaClienteContratoDigital", new object[] {
                        Contrato,
                        ContratoSpecified,
                        Usuario,
                        Password}, this.ConsultaClienteContratoDigitalOperationCompleted, userState);
        }
        
        private void OnConsultaClienteContratoDigitalOperationCompleted(object arg) {
            if ((this.ConsultaClienteContratoDigitalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaClienteContratoDigitalCompleted(this, new ConsultaClienteContratoDigitalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IServicioDebito/ModificarDatosContratoDigital", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ModificarDatosContratoDigital(int Contrato, [System.Xml.Serialization.XmlIgnoreAttribute()] bool ContratoSpecified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string NumeroCuenta, [System.Xml.Serialization.XmlElementAttribute("TipoCuenta")] int TipoCuenta1, [System.Xml.Serialization.XmlElementAttribute("TipoCuenta")] [System.Xml.Serialization.XmlIgnoreAttribute()] bool TipoCuenta1Specified, [System.Xml.Serialization.XmlElementAttribute("IdBanco")] int IdBanco1, [System.Xml.Serialization.XmlElementAttribute("IdBanco")] [System.Xml.Serialization.XmlIgnoreAttribute()] bool IdBanco1Specified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string DireccionIp, [System.Xml.Serialization.XmlElementAttribute("FechaDebito")] int FechaDebito1, [System.Xml.Serialization.XmlElementAttribute("FechaDebito")] [System.Xml.Serialization.XmlIgnoreAttribute()] bool FechaDebito1Specified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Usuario, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Password) {
            object[] results = this.Invoke("ModificarDatosContratoDigital", new object[] {
                        Contrato,
                        ContratoSpecified,
                        NumeroCuenta,
                        TipoCuenta1,
                        TipoCuenta1Specified,
                        IdBanco1,
                        IdBanco1Specified,
                        DireccionIp,
                        FechaDebito1,
                        FechaDebito1Specified,
                        Usuario,
                        Password});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ModificarDatosContratoDigitalAsync(int Contrato, bool ContratoSpecified, string NumeroCuenta, int TipoCuenta1, bool TipoCuenta1Specified, int IdBanco1, bool IdBanco1Specified, string DireccionIp, int FechaDebito1, bool FechaDebito1Specified, string Usuario, string Password) {
            this.ModificarDatosContratoDigitalAsync(Contrato, ContratoSpecified, NumeroCuenta, TipoCuenta1, TipoCuenta1Specified, IdBanco1, IdBanco1Specified, DireccionIp, FechaDebito1, FechaDebito1Specified, Usuario, Password, null);
        }
        
        /// <remarks/>
        public void ModificarDatosContratoDigitalAsync(int Contrato, bool ContratoSpecified, string NumeroCuenta, int TipoCuenta1, bool TipoCuenta1Specified, int IdBanco1, bool IdBanco1Specified, string DireccionIp, int FechaDebito1, bool FechaDebito1Specified, string Usuario, string Password, object userState) {
            if ((this.ModificarDatosContratoDigitalOperationCompleted == null)) {
                this.ModificarDatosContratoDigitalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnModificarDatosContratoDigitalOperationCompleted);
            }
            this.InvokeAsync("ModificarDatosContratoDigital", new object[] {
                        Contrato,
                        ContratoSpecified,
                        NumeroCuenta,
                        TipoCuenta1,
                        TipoCuenta1Specified,
                        IdBanco1,
                        IdBanco1Specified,
                        DireccionIp,
                        FechaDebito1,
                        FechaDebito1Specified,
                        Usuario,
                        Password}, this.ModificarDatosContratoDigitalOperationCompleted, userState);
        }
        
        private void OnModificarDatosContratoDigitalOperationCompleted(object arg) {
            if ((this.ModificarDatosContratoDigitalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ModificarDatosContratoDigitalCompleted(this, new ModificarDatosContratoDigitalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IServicioDebito/GuardarClienteContratoDigital", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GuardarClienteContratoDigital(int Contrato, [System.Xml.Serialization.XmlIgnoreAttribute()] bool ContratoSpecified, [System.Xml.Serialization.XmlElementAttribute("IdBanco")] int IdBanco1, [System.Xml.Serialization.XmlElementAttribute("IdBanco")] [System.Xml.Serialization.XmlIgnoreAttribute()] bool IdBanco1Specified, [System.Xml.Serialization.XmlElementAttribute("TipoCuenta")] int TipoCuenta1, [System.Xml.Serialization.XmlElementAttribute("TipoCuenta")] [System.Xml.Serialization.XmlIgnoreAttribute()] bool TipoCuenta1Specified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string NumeroCuenta, [System.Xml.Serialization.XmlElementAttribute("CanalIngreso")] int CanalIngreso1, [System.Xml.Serialization.XmlElementAttribute("CanalIngreso")] [System.Xml.Serialization.XmlIgnoreAttribute()] bool CanalIngreso1Specified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string DireccionIp, [System.Xml.Serialization.XmlElementAttribute("FechaDebito")] int FechaDebito1, [System.Xml.Serialization.XmlElementAttribute("FechaDebito")] [System.Xml.Serialization.XmlIgnoreAttribute()] bool FechaDebito1Specified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Usuario, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Password) {
            object[] results = this.Invoke("GuardarClienteContratoDigital", new object[] {
                        Contrato,
                        ContratoSpecified,
                        IdBanco1,
                        IdBanco1Specified,
                        TipoCuenta1,
                        TipoCuenta1Specified,
                        NumeroCuenta,
                        CanalIngreso1,
                        CanalIngreso1Specified,
                        DireccionIp,
                        FechaDebito1,
                        FechaDebito1Specified,
                        Usuario,
                        Password});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GuardarClienteContratoDigitalAsync(int Contrato, bool ContratoSpecified, int IdBanco1, bool IdBanco1Specified, int TipoCuenta1, bool TipoCuenta1Specified, string NumeroCuenta, int CanalIngreso1, bool CanalIngreso1Specified, string DireccionIp, int FechaDebito1, bool FechaDebito1Specified, string Usuario, string Password) {
            this.GuardarClienteContratoDigitalAsync(Contrato, ContratoSpecified, IdBanco1, IdBanco1Specified, TipoCuenta1, TipoCuenta1Specified, NumeroCuenta, CanalIngreso1, CanalIngreso1Specified, DireccionIp, FechaDebito1, FechaDebito1Specified, Usuario, Password, null);
        }
        
        /// <remarks/>
        public void GuardarClienteContratoDigitalAsync(int Contrato, bool ContratoSpecified, int IdBanco1, bool IdBanco1Specified, int TipoCuenta1, bool TipoCuenta1Specified, string NumeroCuenta, int CanalIngreso1, bool CanalIngreso1Specified, string DireccionIp, int FechaDebito1, bool FechaDebito1Specified, string Usuario, string Password, object userState) {
            if ((this.GuardarClienteContratoDigitalOperationCompleted == null)) {
                this.GuardarClienteContratoDigitalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGuardarClienteContratoDigitalOperationCompleted);
            }
            this.InvokeAsync("GuardarClienteContratoDigital", new object[] {
                        Contrato,
                        ContratoSpecified,
                        IdBanco1,
                        IdBanco1Specified,
                        TipoCuenta1,
                        TipoCuenta1Specified,
                        NumeroCuenta,
                        CanalIngreso1,
                        CanalIngreso1Specified,
                        DireccionIp,
                        FechaDebito1,
                        FechaDebito1Specified,
                        Usuario,
                        Password}, this.GuardarClienteContratoDigitalOperationCompleted, userState);
        }
        
        private void OnGuardarClienteContratoDigitalOperationCompleted(object arg) {
            if ((this.GuardarClienteContratoDigitalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GuardarClienteContratoDigitalCompleted(this, new GuardarClienteContratoDigitalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void IdBancoCompletedEventHandler(object sender, IdBancoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IdBancoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IdBancoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void TipoCuentaCompletedEventHandler(object sender, TipoCuentaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TipoCuentaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TipoCuentaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void FechaDebitoCompletedEventHandler(object sender, FechaDebitoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FechaDebitoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FechaDebitoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void CanalIngresoCompletedEventHandler(object sender, CanalIngresoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CanalIngresoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CanalIngresoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ConsultaClienteCompletedEventHandler(object sender, ConsultaClienteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaClienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaClienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GuardarClienteCompletedEventHandler(object sender, GuardarClienteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GuardarClienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GuardarClienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ModificarDatosCompletedEventHandler(object sender, ModificarDatosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ModificarDatosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ModificarDatosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ConsultaClientePrenotaCompletedEventHandler(object sender, ConsultaClientePrenotaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaClientePrenotaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaClientePrenotaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ConsultaClienteContratoDigitalCompletedEventHandler(object sender, ConsultaClienteContratoDigitalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaClienteContratoDigitalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaClienteContratoDigitalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ModificarDatosContratoDigitalCompletedEventHandler(object sender, ModificarDatosContratoDigitalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ModificarDatosContratoDigitalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ModificarDatosContratoDigitalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GuardarClienteContratoDigitalCompletedEventHandler(object sender, GuardarClienteContratoDigitalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GuardarClienteContratoDigitalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GuardarClienteContratoDigitalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591