//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DebitoAutomatico.PS {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecursosDebito {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursosDebito() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DebitoAutomatico.PS.RecursosDebito", typeof(RecursosDebito).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El parametro se actualizo correctamente.
        /// </summary>
        internal static string ActualizarParametro {
            get {
                return ResourceManager.GetString("ActualizarParametro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya se genero un archivo con estos filtros a traves del banco: .
        /// </summary>
        internal static string ArchivoGenerado {
            get {
                return ResourceManager.GetString("ArchivoGenerado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El cliente se encuentra un estado diferente, para generar archivo manual.
        /// </summary>
        internal static string ArchivoManual {
            get {
                return ResourceManager.GetString("ArchivoManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Existen contratos pendientes para generar archivo manual.
        /// </summary>
        internal static string ArchivoManualPendiente {
            get {
                return ResourceManager.GetString("ArchivoManualPendiente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Porfavor primero procese los archivos pendientes, antes de generar un archivo de: .
        /// </summary>
        internal static string ArchivosPendientes {
            get {
                return ResourceManager.GetString("ArchivosPendientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha encontrado la entidad bancaria..
        /// </summary>
        internal static string BancoNoExiste {
            get {
                return ResourceManager.GetString("BancoNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha borrado el Banco con éxito..
        /// </summary>
        internal static string BorrarBanco {
            get {
                return ResourceManager.GetString("BorrarBanco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El parametro se borro correctamente.
        /// </summary>
        internal static string BorrarParametro {
            get {
                return ResourceManager.GetString("BorrarParametro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario se borro correctamente.
        /// </summary>
        internal static string BorrarUsuario {
            get {
                return ResourceManager.GetString("BorrarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se eliminó el campo exitosamente.
        /// </summary>
        internal static string CampoEliminado {
            get {
                return ResourceManager.GetString("CampoEliminado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El cliente cuenta con cesiones.
        /// </summary>
        internal static string Cesiones {
            get {
                return ResourceManager.GetString("Cesiones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Prenota rechazada, pero ya fue aprobada por el otro banco.
        /// </summary>
        internal static string CienteAcepado {
            get {
                return ResourceManager.GetString("CienteAcepado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contrato N°:.
        /// </summary>
        internal static string Contrato {
            get {
                return ResourceManager.GetString("Contrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a se encuentra en estado Prenota en Proceso ó Débito en Proceso y no se puede modificar.
        /// </summary>
        internal static string ContratoDebitoProceso {
            get {
                return ResourceManager.GetString("ContratoDebitoProceso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha eliminado la información de Inconsistencias en débito automático..
        /// </summary>
        internal static string ContratoEliminado {
            get {
                return ResourceManager.GetString("ContratoEliminado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solo se pueden ingresar contratos a Débito Automático en Estados Vigente, Mora o Reemplazado.
        /// </summary>
        internal static string ContratoEstados {
            get {
                return ResourceManager.GetString("ContratoEstados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha exportado la información correctamente..
        /// </summary>
        internal static string ContratoExportado {
            get {
                return ResourceManager.GetString("ContratoExportado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  ya fue ingresado como Débito Automático Inconsistente.
        /// </summary>
        internal static string ContratoInconsistente {
            get {
                return ResourceManager.GetString("ContratoInconsistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ya fue ingresado para realizarle el Débito Automático.
        /// </summary>
        internal static string ContratoIngresado {
            get {
                return ResourceManager.GetString("ContratoIngresado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contrato agregado para generar archivo!!!.
        /// </summary>
        internal static string ContratoManual {
            get {
                return ResourceManager.GetString("ContratoManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contrato fue eliminado con éxito!!!.
        /// </summary>
        internal static string ContratoManualEliminado {
            get {
                return ResourceManager.GetString("ContratoManualEliminado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contrato ya fue agregado para generar archivo manual!!!.
        /// </summary>
        internal static string ContratoManualYaExiste {
            get {
                return ResourceManager.GetString("ContratoManualYaExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontro el contrato N°:.
        /// </summary>
        internal static string ContratoNoExiste {
            get {
                return ResourceManager.GetString("ContratoNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a no contiene información de Débito Automático.
        /// </summary>
        internal static string ContratoNoGuardado {
            get {
                return ResourceManager.GetString("ContratoNoGuardado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a por sus condiciones no se puede prenotificar.
        /// </summary>
        internal static string ContratoNoSICO {
            get {
                return ResourceManager.GetString("ContratoNoSICO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a puede ser creado para realizarle el Débito Automático.
        /// </summary>
        internal static string ContratoPuedeCrearse {
            get {
                return ResourceManager.GetString("ContratoPuedeCrearse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solo se puede guardar el contrato una sola vez.
        /// </summary>
        internal static string ContratoYaGuardado {
            get {
                return ResourceManager.GetString("ContratoYaGuardado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se puede crear la entidad bancaria con código.
        /// </summary>
        internal static string CrearBanco {
            get {
                return ResourceManager.GetString("CrearBanco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar solo un registro para realizar este proceso.
        /// </summary>
        internal static string Devoluciones {
            get {
                return ResourceManager.GetString("Devoluciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este cliente tiene un día habil mayor al de hoy, el cual es el:.
        /// </summary>
        internal static string DiaHabil {
            get {
                return ResourceManager.GetString("DiaHabil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usted mismo se no se puede eliminar.
        /// </summary>
        internal static string EliminarMismoUsuario {
            get {
                return ResourceManager.GetString("EliminarMismoUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha encontrado la entidad bancaria llamada.
        /// </summary>
        internal static string EntidadBancaria {
            get {
                return ResourceManager.GetString("EntidadBancaria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrio un error al actualizar el contrato: .
        /// </summary>
        internal static string ErrorActualizaEstado {
            get {
                return ResourceManager.GetString("ErrorActualizaEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se logro agregar la Respuesta con Codigo.
        /// </summary>
        internal static string ErrorCodigo {
            get {
                return ResourceManager.GetString("ErrorCodigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrio un error, porfavor comuniquese con el administrador.
        /// </summary>
        internal static string ErrorProceso {
            get {
                return ResourceManager.GetString("ErrorProceso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  se encuentra en estado .
        /// </summary>
        internal static string EstadoContrato {
            get {
                return ResourceManager.GetString("EstadoContrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede inactivar el banco porque ya es convenio de un banco, porfavor retire el convenio para inactivar.
        /// </summary>
        internal static string ExisteConvenio {
            get {
                return ResourceManager.GetString("ExisteConvenio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede eliminar, porque ya esta siendo utilizado por un cliente.
        /// </summary>
        internal static string FechaDebito {
            get {
                return ResourceManager.GetString("FechaDebito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Es necesario colocar la informmación completa.
        /// </summary>
        internal static string FechaSuspension {
            get {
                return ResourceManager.GetString("FechaSuspension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe escoger la forma de cancelación..
        /// </summary>
        internal static string Formato {
            get {
                return ResourceManager.GetString("Formato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor selecciona la información completa.
        /// </summary>
        internal static string InformacionIncompleta {
            get {
                return ResourceManager.GetString("InformacionIncompleta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede cambiar el estado del contrato a: .
        /// </summary>
        internal static string NoCambioEstado {
            get {
                return ResourceManager.GetString("NoCambioEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontro información con los datos ingresados.
        /// </summary>
        internal static string NoExisteInformacion {
            get {
                return ResourceManager.GetString("NoExisteInformacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No existen registro para realizar la renovación, por favor validar.
        /// </summary>
        internal static string NoHayRenovaciones {
            get {
                return ResourceManager.GetString("NoHayRenovaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este tipo de parametro ya existe, por favor ingrese uno diferente.
        /// </summary>
        internal static string ParametroExiste {
            get {
                return ResourceManager.GetString("ParametroExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  tiene un actualización pendiente desde el APP o la pagina web y no se puede modificar.
        /// </summary>
        internal static string PendienteActualizacion {
            get {
                return ResourceManager.GetString("PendienteActualizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este modulo solo puede ser utilizado por un perfil autorizado.
        /// </summary>
        internal static string PerfilAutorizado {
            get {
                return ResourceManager.GetString("PerfilAutorizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha guardado la información correctamente..
        /// </summary>
        internal static string ProcesoExistoso {
            get {
                return ResourceManager.GetString("ProcesoExistoso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha reanudado correctamente el mes de .
        /// </summary>
        internal static string Reanudacion {
            get {
                return ResourceManager.GetString("Reanudacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Existen clientes en Debito en proceso.
        /// </summary>
        internal static string ReversionNo {
            get {
                return ResourceManager.GetString("ReversionNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encuentra la ruta del archivo o existen problemas de permisos!!!.
        /// </summary>
        internal static string RutaIncorrecta {
            get {
                return ResourceManager.GetString("RutaIncorrecta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe escoger al menos un filtro de busqueda.
        /// </summary>
        internal static string SinFiltro {
            get {
                return ResourceManager.GetString("SinFiltro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solo se puede realizar suspensión temporal a clientes Suscriptores o Cuotas por devolver.
        /// </summary>
        internal static string SuspendidoTemporal {
            get {
                return ResourceManager.GetString("SuspendidoTemporal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  se encuentra en TERMINACIÓN DE CONTRATO y no se puede ingresar..
        /// </summary>
        internal static string TerminacionContrato {
            get {
                return ResourceManager.GetString("TerminacionContrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solo se permiten archivos con extension .txt o .inf!.
        /// </summary>
        internal static string TipoArchivo {
            get {
                return ResourceManager.GetString("TipoArchivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solo se pueden ingresar contratos a Débito Automático con tipos de clientes Suscriptores, Adjudicados o Ganadores.
        /// </summary>
        internal static string TiposClientes {
            get {
                return ResourceManager.GetString("TiposClientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar por lo menos un tipo de contrato.
        /// </summary>
        internal static string TiposContrato {
            get {
                return ResourceManager.GetString("TiposContrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario se actualizo correctamente.
        /// </summary>
        internal static string UsuarioActualizado {
            get {
                return ResourceManager.GetString("UsuarioActualizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debito Parcial, el valor maximo que se puede debitar al cliente es de: .
        /// </summary>
        internal static string ValorMaximo {
            get {
                return ResourceManager.GetString("ValorMaximo", resourceCulture);
            }
        }
    }
}
